### ISSUE TITLE
После ввода ключа показывается чёрный экран

### ISSUE THREAD

**Issue by lucky-ly** [dq-server/dq-server.github.io#2]
меню, статус сервера и кнопки действия показываются только после перезагрузки страницы

**Comment by deltaidea** [comment]
Хм, не могу воспроизвести. Попробуй ещё раз? Очисти localStorage, если хочешь с нуля посмотреть. Можешь вбить любую строку с двоеточием, просто получишь `AWS Was Not Able To Validate The Provided Access Credentials`.

**Comment by lucky-ly** [comment]
Хм. Я тоже не могу теперь. Может, дело в том, что сейчас на сервере есть люди и он быстро пингуется. Проверю, когда он будет выключен, и если не повторится, закрою
